In [3]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view

In [4]:
mp_key = "nbKtMcNjVctWQexVKEJTiT489Bo6oYrr"
mp_id = "mp-11869"

In [5]:
#Récupération de la structure
with MPRester(mp_key) as m:
    structure = m.get_structure_by_material_id(mp_id)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Symétrie

In [6]:
sym = SpacegroupAnalyzer(structure).get_symmetry_operations()

#Atomes
Hf = [0,0,0]
Sn = [0.5,0,0]
Pd = [0.25,0.25,0.75]

#Symétries
sym1 = sym[26] #plan miroir (x,y,z)->(z,y,x)
sym2 = sym[40] #rotation d'ordre 3 (x,y,z)->(z,x,y)
sym3 = sym[11] #roto-inversion (x,y,z)->(-x-y-z,y,z)

### Plan miroir sur Hf

In [9]:
print("On applique une symétrie plan miroir à l'atome Hf ([0,0,0]) :")
print(sym1.rotation_matrix, "•", Hf, "+", sym1.translation_vector)
print("Ce qui donne comme coordonnées finale : {}\n".format(sym1.operate(Hf)))
view1 = quick_view(structure, conventional=True)
display(view1)
view1.script("draw symop 27 {atomno=1}")

On applique une symétrie plan miroir à l'atome Hf ([0,0,0]) :
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] • [0, 0, 0] + [0. 0. 0.]
Ce qui donne comme coordonnées finale : [0. 0. 0.]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Symétrie 2 sur Sn

In [17]:
print("On applique une rotation d'ordre 3 à l'atome Sn ([0.5,0,0]) :")
print(sym2.rotation_matrix, "•", Sn, "+", sym2.translation_vector)
print("Ce qui donne comme coordonnées finale : {}\n".format(sym2.operate(Sn)))
view2 = quick_view(structure, conventional=True)
display(view2)
view2.script("draw symop 41 {atomno=6}")

On applique une rotation d'ordre 3 à l'atome Sn ([0.5,0,0]) :
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] • [0.5, 0, 0] + [0. 0. 0.]
Ce qui donne comme coordonnées finale : [0.  0.5 0. ]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Symétrie 3 sur Pd 

In [19]:
print("On applique une roto-inversion à l'atome Pd ([0.25,0.25,0.75]) :")
print(sym3.rotation_matrix, "•", Pd, "+", sym3.translation_vector)
print("Ce qui donne comme coordonnées finale : {}\n".format(sym3.operate(Pd)))
view3 = quick_view(structure, conventional=True)
display(view3)
view3.script("draw symop 11 {atomno=10}")

On applique une roto-inversion à l'atome Pd ([0.25,0.25,0.75]) :
[[-1. -1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] • [0.25, 0.25, 0.75] + [0. 0. 0.]
Ce qui donne comme coordonnées finale : [-1.25  0.25  0.75]



JsmolView(layout=Layout(align_self='stretch', height='400px'))